### PR TITLE
[Android] Correct versioning, increase gradle version, new launcher icon, configs clean up

### PR DESCRIPTION
**Pull request by foxtrotdev**
feat: correct versioning (moved to gradle file)
feat: increased gradle version to 7.2.1
feat: add launcher icons (from Wikipedia - https://de.wikipedia.org/wiki/Datei:Quake_III_Arena_Logo.svg - author: unknown)

### CODE REVIEW

**Comment by foxtrotdev** [comment]
+feat: cleaned up the AndroidManifest.xml file

**Comment by lvonasek** [comment]
Note that targeting over Android API 29 will cause compatibility issues once Quest gets updated to Android 11 or higher.

**Comment by foxtrotdev** [comment]
> Note that targeting over Android API 29 will cause compatibility issues once Quest gets updated to Android 11 or higher.

I could change it to 29 then. Do you have any source describing this problem?

**Comment by lvonasek** [comment]
https://developer.android.com/about/versions/11/privacy/storage

**Comment by foxtrotdev** [comment]
In short it requires declaration what paths are going to be used. It could be handled nicely. Right now I have not Android 11 on my Oculus so I will just wait till my update.

**Comment by foxtrotdev** [comment]
OK, I reverted my change to the previous sdk version.

**Comment by DrBeef** [comment]
Thank-you!

**Pull request merged**
